gui:

  #item start menu
  start:
    - item: target
      slot: 21
      name: Выберите тип клана
      lore:

    - item: paper
      slot: 23
      name: Просмотр списка кланова
      lore:

    - item: arrow
      slot: 44
      name: Выход из меню
      lore:

  #item choose menu
  choose:
    - item: iron_sword
      slot: 20
      name: PvP клан
      lore:

    - item: iron_hoe
      slot: 24
      name: PvE клан
      lore:

    - item: arrow
      slot: 44
      name: Выход из меню
      lore:

  unique_effects:
    - item: COMPARATOR
      slot: 46
      name: Включение нескольких эффектов
      lore:

    - item: GRAY_DYE
      slot: 48
      name: Предыдущая страница
      lore:

    - item: GREEN_DYE
      slot: 50
      name: Вперед
      lore:

    - item: BARRIER
      slot: 51
      name: Отключение всех эффектов
      lore:

    - item: iron_sword
      slot: 10
      name: Клановый эффект
      lore:

    - item: player_head
      slot: 4
      name: Голова создателя
      lore:

    - item: ARROW
      slot: 7
      name: Назад
      lore:









  #item PVP clans
  PVP:
    - item: compass
      slot: 23
      name: "§b⿻ Помощь по клановой системе ⿻"
      lore:
        - "§b| /clan money §f— баланс клана по монетам"
        - "§b| /clan invest <сумма> §f— пополнить казну клана"
        - "§b| /clan withdraw <сумма> §f— снять деньги с казны клана"
        - "§b| /clan take <сумма> §f — снять деньги с казны клана"
        - ""
        - "§b| /clan members §f— участники клана"
        - "§b| /clan invite <ник> §f— пригласить игрока в клан"
        - "§b| /clan kick <ник> §f— удалить игрока из клана"
        - ""
        - "§b| /clan delete §f— удалить клан"
        - "§b| /clan newleader <ник> §f— передать лидера клана"
        - ""
        - "§b| /clan glow §f— выбор подсветки вашей брони"
        - "§b| /clan captures §f— открыть меню Хатынок"
        - "§b| /clan pvp §f— вкл./выкл. урон по союзникам"
        - "§b| /clan list §f— просмотр списка кланов"
        - "§b| /clan chat §f— переключить свой чат на клановый чат"
        - "§b| /clan sethome §f— установить клан хом"
        - "§b| /clan home §f— телепортироваться на клан хом"
        - "§b| /clan leave §f— покинуть клан"

    - item: player_head
      slot: 21
      name: Информация по клану
      lore:

    - item: paper
      slot: 19
      name: "§b⿻ Список всех кланов ⿻"
      lore:
         - "§b| §fПодробная информация"
         - "§b| §fпо каждому клану на сервере."
         - ""
         - "§b▶ §fНажмите, чтобы открыть раздел"

    - item: structure_void
      slot: 10
      name: "§4▶ §fЭтот раздел §4недоступен."
      lore:
        - " "
        - "§fТип вашего клана не позволяет"
        - "§fоткрывать этот раздел."

    - item: potion
      slot: 28
      name: "§b⿻ Стакнуть зелья ⿻"
      lore:
        - " "
        - "§b| §fВ данном разделе ты можешь"
        - "§b| §fстакнуть зелья, чтобы"
        - "§b| §fэкономить место в инвентаре."
        - "   §b• §fЧтобы стакнуть зелья надо:"
        - "       §6— 5 уровень §fклана"
        - " "
        - "§b▶ §fНажмите, чтобы открыть раздел"

    - item: chorus_flower
      slot: 25
      name: "§b⿻ Шальной ивент §b⿻"
      lore:
        - "§b Цель:"
        - "§b|{task}"
        - "§b•§f Награда:§6 {reward}"
        - "§b•§f Статус: {status}"

    - item: end_crystal
      slot: 2
      name: "§b⿻ Прокачать клан ⿻"
      lore:
        - " "
        - "§b | §fВ данном разделе ты можешь"
        - "§b | §fприобрести клановые очки за сапфиры."
        - "§b | §fА также увеличивать уровень клана,"
        - "§b | §fвыполняя необходимые требования."
        - "§b |"
        - "§b | §fЧем больше очков и выше уровень,"
        - "§b | §fтем больше стратегических преимуществ"
        - "§b | §fполучает ваш клан."
        - " "
        - "§b▶ §bНажмите, чтобы открыть раздел"

    - item: crimson_fungus
      slot: 6
      name: "§6⿻ Уникальные эффекты ⿻"
      lore:
        - " "
        - "§6| §fВ этом разделе ты можешь §6приобрести"
        - "§6| §fили улучшить §6полезные эффекты,"
        - "§6| §fкоторые распространяются"
        - "§6| §fна всех членов клана."
        - "§6| "
        - "§6| §fКлановые эффекты различаются"
        - "§6| §fв зависимости от типа вашего клана."
        - " "
        - "§6▶ §fНажмите, чтобы открыть раздел"

    - item: totem_of_undying
      slot: 42
      name: "§6⿻ Магазин клана ⿻"
      lore:
        - " "
        - "§6| §fЗдесь ты можешь §6приобрести "
        - "§6| уникальные предметы§f и яйца призыва"
        - "§6| §fиз Премиум-Магазина за монетки,"
        - "§6| §fа также рубины."
        - " "
        - "     §6•§f Чтобы открыть магазин надо:"
        - "         §6— 1 500 000 монет §fв казне клана"
        - "         §6— 1 уровень §fклана"
        - "     §f* Для разблокировки создатель клана"
        - "     §f  должен нажать по данной иконке."
        - " "
        - "§6▶ §fНажмите, чтобы разблокировать"

    - item: gold_ingot
      slot: 38
      name: "§b⿻ Казна клана ⿻"
      lore:
        - "§b| §fВ данном разделе ты можешь"
        - "§b| §fпополнять деньгами"
        - "§b| §fклановый баланс, или же"
        - "§b| §fскоммуниздить деньги§7."
        - ""
        - "§b| §fВалюта необходима для покупки"
        - "§b| §fразличных клановых преимуществ."
        - ""
        - "§b▶ §fНажмите, чтобы открыть раздел"

    - item: netherite_sword
      slot: 16
      name: "§6⿻ Клановый поединок ⿻"
      lore:
        - " "
        - "§6|     §f* §6За 10 минут до начала §fмероприятия открывается"
        - "§6|     §fрегистрация на ивент — по нажатию на данную иконку;"
        - "§6|     §f* Для участия в поединке"
        - "§6|     §6Создателю или Старшине §fнеобходимо"
        - "§6|     §fсобрать команду §fсмельчаков,"
        - "§6|     §fсостоящую из участников своего клана;"
        - "§6|     §f* Поединок §6будет проведён §fна случайном «Классике»,"
        - "§6|     §fгде §6может действовать §fодно из ограничений или"
        - "§6|     §fодна из особенностей конкретного номера «Классика»."
        - "§6|     §fНомер объявляется за 10 минут до начала ивента."

    - item: diamond_horse_armor
      slot: 34
      name: Хатынки
      lore:

    - item: arrow
      slot: 53
      name: Выйти из меню
      lore:

  #item PVE clans
  PVE:

    - item: compass
      slot: 23
      name: "§b⿻ Помощь по клановой системе ⿻"
      lore:
        - " "
        - "§b| /clan money §f— баланс клана по монетам"
        - "§b| /clan invest <сумма> §f— пополнить казну клана"
        - "§b| /clan withdraw <сумма> §f— снять деньги с казны клана"
        - "§b| /clan take <сумма> §f — снять деньги с казны клана"
        - ""
        - "§b| /clan members §f— участники клана"
        - "§b| /clan invite <ник> §f— пригласить игрока в клан"
        - "§b| /clan kick <ник> §f— удалить игрока из клана"
        - ""
        - "§b| /clan delete §f— удалить клан"
        - "§b| /clan newleader <ник> §f— передать лидера клана"
        - ""
        - "§b| /clan glow §f— выбор подсветки вашей брони"
        - "§b| /clan captures §f— открыть меню Хатынок"
        - "§b| /clan pvp §f— вкл./выкл. урон по союзникам"
        - "§b| /clan list §f— просмотр списка кланов"
        - "§b| /clan chat §f— переключить свой чат на клановый чат"
        - "§b| /clan sethome §f— установить клан хом"
        - "§b| /clan home §f— телепортироваться на клан хом"
        - "§b| /clan leave §f— покинуть клан"

    - item: player_head
      slot: 21
      name: Информация по клану
      lore:

    - item: paper
      slot: 19
      name: "§b⿻ Список всех кланов ⿻"
      lore:
         - " "
         - "§b| §fПодробная информация"
         - "§b| §fпо каждому клану на сервере."
         - " "
         - "§b▶ §fНажмите, чтобы открыть раздел"

    - item: leather_chestplate
      slot: 10
      name: "§b⿻  Цвет брони ⿻"
      lore:
        - " "
        - "§b| §fВ данном разделе ты"
        - "§b| §fможешь выбрать цвет брони"
        - "§b| §fдля подсветки соклановцев"
        - " "
        - "§b▶ §fНажмите, чтобы открыть раздел"

    - item: potion
      slot: 28
      name: "§b⿻ Стакнуть зелья ⿻"
      lore:
        - " "
        - "§b| §fВ данном разделе ты можешь"
        - "§b| §fстакнуть зелья, чтобы"
        - "§b| §fэкономить место в инвентаре."
        - "   §b• §fЧтобы стакнуть зелья надо:"
        - "       §6— 5 уровень §fклана"
        - " "
        - "§b▶ §fНажмите, чтобы открыть раздел"

    - item: chorus_flower
      slot: 25
      name: "§b⿻ Шальной ивент ⿻"
      lore:
        - " "
        - "§b| §fОсобый ивент, который случайным образом"
        - "§b| §fвыдаёт §bспециальное задание§f для клана."
        - " "
        - "§b| §fТип вашего клана позволяет"
        - "§b| 12 раз в сутки§f получать задание."
        - " "
        - "      §f* Задание выдаётся"
        - "      §f  с 10:00 до 22:00 по МСК."
        - " "
        - "§b• §fНаграда: §61 очко клана"
        - "§b• §fСтатус: §6Ожидание"

    - item: end_crystal
      slot: 2
      name: "§b⿻ Прокачать клан ⿻"
      lore:
        - " "
        - "§b | §fВ данном разделе ты можешь"
        - "§b | §fприобрести клановые очки за сапфиры."
        - "§b | §fА также увеличивать уровень клана,"
        - "§b | §fвыполняя необходимые требования."
        - "§b |"
        - "§b | §fЧем больше очков и выше уровень,"
        - "§b | §fтем больше стратегических преимуществ"
        - "§b | §fполучает ваш клан."
        - " "
        - "§b▶ §bНажмите, чтобы открыть раздел"


    - item: crimson_fungus
      slot: 6
      name: "§6⿻ Уникальные эффекты ⿻"
      lore:
        - " "
        - "§6| §fВ этом разделе ты можешь §6приобрести"
        - "§6| §fили улучшить §6полезные эффекты,"
        - "§6| §fкоторые распространяются"
        - "§6| §fна всех членов клана."
        - "§6| "
        - "§6| §fКлановые эффекты различаются"
        - "§6| §fв зависимости от типа вашего клана."
        - " "
        - "§6▶ §fНажмите, чтобы открыть раздел"

    - item: totem_of_undying
      slot: 42
      name: "§6⿻ Магазин клана ⿻"
      lore:
        - " "
        - "§6| §fЗдесь ты можешь §6приобрести "
        - "§6| уникальные предметы§f и яйца призыва"
        - "§6| §fиз Премиум-Магазина за монетки,"
        - "§6| §fа также рубины."
        - " "
        - "     §6•§f Чтобы открыть магазин надо:"
        - "         §6— 1 500 000 монет §fв казне клана"
        - "         §6— 1 уровень §fклана"
        - "     §f* Для разблокировки создатель клана"
        - "     §f  должен нажать по данной иконке."
        - " "
        - "§6▶ §fНажмите, чтобы разблокировать"


    - item: gold_ingot
      slot: 38
      name: "§b⿻ Казна клана ⿻"
      lore:
        - "§b| §fВ данном разделе ты можешь"
        - "§b| §fпополнять деньгами"
        - "§b| §fклановый баланс, или же"
        - "§b| §fскоммуниздить деньги§7."
        - ""
        - "§b| §fВалюта необходима для покупки"
        - "§b| §fразличных клановых преимуществ."
        - ""
        - "§b▶ §fНажмите, чтобы открыть раздел"

    - item: structure_void
      slot: 10
      name: "§4▶ §fЭтот раздел §4недоступен."
      lore:
        - " "
        - "§fТип вашего клана не позволяет"
        - "§fоткрывать этот раздел."

    - item: structure_void
      slot: 10
      name: "§4▶ §fЭтот раздел §4недоступен."
      lore:
        - " "
        - "§fТип вашего клана не позволяет"
        - "§fоткрывать этот раздел."

    - item: arrow
      slot: 53
      name: "&4▶ &fЗакрыть меню"
      lore:

